version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%d-%b-%y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: scrapper_process.log
  email:
    class: logging.handlers.SMTPHandler
    level: ERROR
    mailhost: smtp.gmail.com
    fromaddr: prost.jb@gmail.com
    toaddrs: prost.jb@gmail.com
    subject: LinkedIn Scrapping ERROR
    credentials: [prost.jb@gmail.com, banane1728]
    secure: []
root:
  level: DEBUG
  handlers: [console, file, email]
  propagate: True